### ISSUE TITLE
Lecture - Sep 20, 2024

### ISSUE THREAD

**Issue by marmanios** [jinalkast/capstone#1]
**Topic**: Requirements Documentation (pt. 2)
**Date and Time**: Friday, September 20th, 2024 @ 12:30pm
**Attendance**
- [ ] Mohammed (Zayn) Abed
- [ ] Maged Armanios
- [ ] Jinal Kasturiarachchi
- [ ] Jane Klavir
- [ ] Harshil Patel

**Questions to Ask**
- How should we pick our project? We have two options and are having difficulty deciding.

**Comment by jinalkast** [comment]
Spoke to Dr. Smith, decided it was best to choose our own original idea, rather than have the extra overhead of working within a competition.
